onboarding = false
[keys]
focus_pane_left = ["prefix+h", "ctrl+alt+h"]
focus_pane_down = ["prefix+j", "ctrl+alt+j"]
focus_pane_up = ["prefix+k", "ctrl+alt+k"]
focus_pane_right = ["prefix+l", "ctrl+alt+l"]

[ui.sound]
enabled = false

[ui]
agent_panel_sort = "spaces"
status_indicators = "symbols"

[theme]
name = "catppuccin"
auto_switch = false
